// src/App.vue
<script setup lang="ts">
import { reactive, ref } from 'vue'
import { generateLoremIpsum } from '@/helpers/generateLoremIpsum'
import { VOCAB } from '@/constants'

import Header from '@/components/Header.vue'
import Button from '@/components/Button.vue'
import Select from '@/components/Select.vue'

const userInput = reactive({
  numParagraphs: 1,
  numSentences: 1,
})

const generatedLoremIpsumArr = ref<string[]>([])

const handleClick = () => {
  const { numParagraphs, numSentences } = userInput
  generatedLoremIpsumArr.value = generateLoremIpsum({
    numParagraphs,
    numSentences,
    vocab: VOCAB,
  })
}
</script>

<template>
  <Header />
  <main class="m-auto max-w-6xl px-6">
    <div class="grid grid-cols-4 gap-6 md:grid-cols-12">
      <div class="order-first col-span-full mb-6 md:col-span-3">
        <div class="mb-6">
          <label for="paragraphs" class="block">Number of paragraphs</label>
          <Select name="numParagraphs" v-model="userInput.numParagraphs" />
        </div>
        <div class="mb-6">
          <label for="paragraphs" class="block">Number of sentences</label>
          <Select name="numSentences" v-model="userInput.numSentences" />
        </div>
        <div>
          <Button @click="handleClick"> Try DMT! </Button>
        </div>
      </div>

      <div class="col-span-full md:col-span-9">
        <p
          v-for="(paragraph, index) in generatedLoremIpsumArr"
          :key="index"
          class="mb-6"
        >
          {{ paragraph }}
        </p>
      </div>
    </div>
  </main>
</template>

// src/App.svelte
<script>
	import Select from './components/Select.svelte';
	import Button from './components/Button.svelte';

	import { generateLoremIpsum } from './utils';

	let loremIpsum = {
		numParagraphs: 1,
		numSentences: 5,
	};

	let text = generateLoremIpsum(1, 5)

	function handleSubmit() {
		const { numParagraphs, numSentences } = loremIpsum;

		text = generateLoremIpsum(numParagraphs, numSentences)
	}
</script>

<main>
	<div class="content">

		<div class="item">
			<form on:submit|preventDefault={handleSubmit}>
				<Select 
					selectTitle="Number of paragraphs" 
					bind:value={loremIpsum.numParagraphs}
				/>
				<Select 
					selectTitle="Number of sentences" 
					bind:value={loremIpsum.numSentences}
				/>
				
				<Button buttonText="Try DMT!"/>
			</form>
		</div>


		<div class="item">
			<div class="text-area">
			{#each text as textItem}
				<p class="paragraph">{textItem}</p>
			{/each}
			</div>
		</div>

	</div>
</main>

<style>
.content {
	display: grid;
	grid-template-columns: 1, 1fr;
	grid-template-rows: 2, 1fr;
	grid-gap: 3em;
	grid-template-areas: 'slot1' 'slot2';
	padding: 2em;
}

@media (min-width: 640px) {
	.content {
		grid-template-areas: 'slot1 slot2';
	}
}

.paragraph:first-child {
	margin-top: 0;
}
</style>
